"""Bundle the presentation folder into a single archive.

Keeps exactly what a slide deck needs: 6 plots, 2 system diagrams, 2 animations,
the numbers behind them, and a README. Large intermediates (model zips, raw
recordings) stay out of the archive.

    PYTHONPATH=python python -m arlamx_v2.pack_presentation
"""
from __future__ import annotations

import json
import zipfile
from pathlib import Path

from arlamx_v2.paths import OUTPUTS

OUT = OUTPUTS / "presentation"
ARCHIVE = OUTPUTS / "ARLAMX_V2_presentation.zip"

# Only these land in the archive; everything else under presentation/ is working data.
INCLUDE_DIRS = ("plots", "diagrams", "animations", "data")
INCLUDE_EXT = {".png", ".pdf", ".svg", ".mp4", ".gif", ".md", ".json", ".csv"}
SKIP_NAMES = {"traces.json", "train.log"}      # traces.json is ~MBs of raw series


def entries():
    rows = []
    readme = OUT / "README.md"
    if readme.exists():
        rows.append((readme, "README.md"))
    for d in INCLUDE_DIRS:
        base = OUT / d
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if not p.is_file() or p.suffix.lower() not in INCLUDE_EXT:
                continue
            if p.name in SKIP_NAMES:
                continue
            rows.append((p, str(p.relative_to(OUT))))
    return rows


def write_readme():
    """Generate the folder README from the result files, so the numbers quoted
    here can never drift from the numbers in the figures."""
    import numpy as np
    from arlamx_v2.bench_production import ALGOS, BUDGETS, cell_label

    D = OUT / "data"
    bake = json.loads((D / "bakeoff.json").read_text())
    infer = json.loads((D / "inference_cost.json").read_text())
    train = json.loads((D / "train_metrics.json").read_text())

    def gaps(algo, bud):
        return [v["gap_index"] for k, v in bake.items()
                if k.startswith(f"{cell_label(algo, bud)} s")]

    def agg(label, key):
        return bake[label]["agg"][key]

    def cell_agg(algo, bud, key):
        vs = [v["agg"][key] for k, v in bake.items()
              if k.startswith(f"{cell_label(algo, bud)} s")]
        return float(np.median(vs))

    # best RL cell by median gap
    best = min((float(np.median(gaps(a, b))), a, b)
               for a in ALGOS for b in BUDGETS if gaps(a, b))
    bg, ba, bb = best

    lines = []
    A = lines.append
    A("# ARLAMX V2.0 — presentation pack")
    A("")
    A("Generated by `arlamx_v2.pack_presentation`. Everything here comes from the runs")
    A("in `outputs/presentation/runs/`, trained on the **post-fix** plant")
    A("(see `ACEnv/Reports/2026-08-20_detailed_v2_fixes_applied.md`).")
    A("")
    A("## Contents")
    A("")
    A("| File | What it shows |")
    A("|---|---|")
    A("| `diagrams/adcs_onboard.*` | The flight ADCS signal chain — sensors to magnetorquers. No simulation. |")
    A("| `diagrams/training_loop.*` | How that same stack is trained and scored. Ground software marked as such. |")
    A("| `plots/fig1_mission_scorecard.*` | Head-to-head on decay, battery band, downlink, actuator energy |")
    A("| `plots/fig2_cost_vs_quality.*` | Compute per decision vs mission quality — the deployability argument |")
    A("| `plots/fig3_learner_and_budget.*` | PPO/SAC/TD3 at 50k and 250k, three seeds each |")
    A("| `plots/fig4_disturbance_observer.*` | The onboard estimate of the aerodynamic torque vs plant truth |")
    A("| `plots/fig5_environment_and_economy.*` | Authority gating, and what each policy spends in actuator energy |")
    A("| `plots/fig6_storm_response.*` | Altitude and battery through a solar storm |")
    A("| `animations/mpc_*.mp4` | The MPC through the storm onset |")
    A(f"| `animations/rl_{ba}_*.mp4` | The trained {ba.upper()} policy through the same storm onset |")
    A("| `data/*.json` | Every number behind the figures |")
    A("")
    A("Each plot is written as both PNG (slides) and PDF (vector, for print).")
    A("")
    A("## Headline numbers")
    A("")
    A("| Policy | gap index | decay (km/d) | battery in band | downlink (min/d) | brownouts | actuator energy (J) | ms/decision |")
    A("|---|---|---|---|---|---|---|---|")
    for lab in ("MPC", "Heuristic"):
        A(f"| {lab} | {bake[lab]['gap_index']:.3f} | {agg(lab,'decay_nominal'):.2f} | "
          f"{agg(lab,'band_pct'):.1f} % | {agg(lab,'downlink_min_d'):.1f} | "
          f"{agg(lab,'brownouts'):.0f} | {agg(lab,'act_energy_J'):.0f} | "
          f"{infer[lab]['ms_per_decision']:.2f} |")
    for a in ALGOS:
        for b in BUDGETS:
            g = gaps(a, b)
            if not g:
                continue
            lab = cell_label(a, b)
            A(f"| {lab} (median of {len(g)} seeds) | {float(np.median(g)):.3f} | "
              f"{cell_agg(a,b,'decay_nominal'):.2f} | {cell_agg(a,b,'band_pct'):.1f} % | "
              f"{cell_agg(a,b,'downlink_min_d'):.1f} | {cell_agg(a,b,'brownouts'):.0f} | "
              f"{cell_agg(a,b,'act_energy_J'):.0f} | "
              f"{infer.get(lab,{}).get('ms_per_decision', float('nan')):.2f} |")
    A("")
    A("gap index = mean normalised distance to the MPC across decay, battery band, brownouts and")
    A("downlink. **0 is the MPC; lower is better; negative would beat it.**")
    A("")
    A("## What the data actually says")
    A("")
    A(f"1. **The sampling MPC is still the best controller on mission quality.** The heuristic advisor")
    A(f"   comes second (gap {bake['Heuristic']['gap_index']:.2f}); no reinforcement-learning run at either budget")
    A(f"   beat either of them. The best learned policy was {ba.upper()} at {bb // 1000}k steps (gap {bg:.2f}).")
    A("")
    ratio = infer["MPC"]["ms_per_decision"] / max(
        float(np.median([infer[cell_label(a, bb)]["ms_per_decision"]
                         for a in ALGOS if cell_label(a, bb) in infer])), 1e-9)
    A(f"2. **Where the network wins is cost.** One MPC decision costs")
    A(f"   {infer['MPC']['ms_per_decision']:.1f} ms because it rolls the dynamics forward many times; the network")
    A(f"   answers in {infer[cell_label(ba, bb)]['ms_per_decision']:.2f} ms at fixed cost — about **{ratio:,.0f}x cheaper**, and")
    A("   unlike the MPC it needs no onboard propagator. That is the difference between a controller")
    A("   that fits a CubeSat duty cycle and one that does not.")
    A("")
    td3_e = cell_agg("td3", BUDGETS[0], "act_energy_J")
    A(f"3. **TD3 is by far the thriftiest actuator user** ({td3_e:.0f} J vs {agg('MPC','act_energy_J'):.0f} J for the MPC and")
    A(f"   {agg('Heuristic','act_energy_J'):.0f} J for the heuristic) — it holds attitude with much less magnetorquer")
    A("   duty, at the cost of orbit-energy performance.")
    A("")
    A("4. **More training made things worse.** Going from 50k to 250k steps degraded every learner on")
    A("   this reward; PPO and SAC start browning the battery out. The extra budget is spent driving")
    A("   drag harder than the power system can support. This is a reward-shaping problem, not a")
    A("   training-length problem.")
    A("")
    A("5. **The published campaign leaderboard is not a fair comparison point.** Its best entry")
    A("   (gap 0.468) was the best of 53 trials over a config sweep, and it was trained against a")
    A("   magnetic field that pointed the wrong way. Re-scored on the corrected plant that same model")
    A("   lands at gap 2.914 with 13 brownouts. Everything here is a fresh, seed-replicated run.")
    A("")
    A("## Reproduce")
    A("")
    A("```bash")
    A("PYTHONPATH=python python -m arlamx_v2.bench_production --stage all   # train + score + trace")
    A("PYTHONPATH=python python -m arlamx_v2.plot_production               # the six figures")
    A("PYTHONPATH=python python -m arlamx_v2.anim_production               # the two animations")
    A("PYTHONPATH=python python -m arlamx_v2.pack_presentation             # this folder + zip")
    A("```")
    A("")
    tw = sum(v.get("wall_s", 0.0) for v in train.values())
    A(f"18 training runs (3 learners x 2 budgets x 3 seeds), {tw/60:.0f} min of training wall time total,")
    A("all on the identical SC_v7 stage-S4 configuration. Plant: 0.44 ms per 300 s decision.")
    (OUT / "README.md").write_text("\n".join(lines) + "\n")
    print("[pack] wrote README.md")


def main():
    write_readme()
    rows = entries()
    if not rows:
        raise SystemExit("nothing to pack — run bench_production / plot_production first")
    with zipfile.ZipFile(ARCHIVE, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for src, arc in rows:
            z.write(src, arcname=f"ARLAMX_V2_presentation/{arc}")
    total = sum(p.stat().st_size for p, _ in rows)
    print(f"[pack] {len(rows)} files, {total/1e6:.1f} MB raw "
          f"-> {ARCHIVE.stat().st_size/1e6:.1f} MB")
    print(f"[pack] {ARCHIVE}")
    manifest = {arc: p.stat().st_size for p, arc in rows}
    (OUT / "data" / "manifest.json").write_text(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
